name: social-network test&deploy

on:
  push:
    branches:
      - master
jobs:
  Tests:
    name: unit tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install deps
        run: yarn

      - name: unit tests
        run: yarn test

  Build:
    name: Build
    runs-on: ubuntu-latest
    needs: Tests
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install deps
        run: yarn

      - name: deploy
        run: yarn deploy
